### ISSUE TITLE
#Error when using Journeymap script in Sponge server

### ISSUE THREAD

**Issue by LANCECHEN117** [edwardg117/ADV-Project#6]
Hi edwardg117, this is error when I am using your journey map script in multiplayer server [Forge 2854, Sponge 2838-730].

It's fine in single player but is not working in multiplayer.

Errors can be seen as follows:
![image](https://user-images.githubusercontent.com/50238182/105069710-45b8f480-5abd-11eb-8b64-c3f442e6de03.png)

Could you help me to fix it?

**Comment by edwardg117** [comment]
I never got around to doing a full test or the script in multiplayer after slava updated it to fix the crash. DO you know what action specifically causes this?

**Comment by edwardg117** [comment]
Okay, I think I've figured out what's causing this. It seems that saving or loading from JSON isn't working properly in ScriptedJourneyMap-1.1.0-beta. I'll report this to slava but the plugin is unsupported so I'll see what I can do for a workaround.

**Comment by edwardg117** [comment]
Just updated the script to [V1.02](https://github.com/edwardg117/ADV-Project/blob/master/EMCA_Scripts/Journeymap%20Waypoint%20Handler.js), I'm fairly certain I got everything working on servers now. Please test and get back to me @LANCECHEN117 .

**Comment by edwardg117** [comment]
I haven't been able to reproduce this issue with the new version so I'm going to call it fixed.
